version: "3.7"
services:
  mongo:
    image: mongo
    networks:
      - todo
    ports:
      - "27017:27017"
  webserver:
    image: webserver:1.1
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: npm run start
    networks:
      - todo
    environment:
      - PORT=5000
      - NODE_ENV=production
    # ports:
    #   - "5000:5000"
  frontend:
    # image: j2_middleware:$CDT_IMAGE_VERSION
    image:  frontend:1.1
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    networks:
      - todo
    environment:
      - PORT=3000
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:3050/backend/api/
    # ports:
    #   - "3000:3000"
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - '3050:80'
    networks:
      - todo
networks:
  todo:
    name: todo

